services:
  ffc-sfd-ahwp-stub:
    build:
      context: .
      target: production
    image: ffc-sfd-ahwp-stub
    container_name: ffc-sfd-ahwp-stub
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfd-ahwp-stub-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      COOKIE_PASSWORD: the-password-must-be-at-least-32-characters-long
      DEFRA_ID_ENABLED: ${DEFRA_ID_ENABLED:-false}
      DEFRA_ID_WELL_KNOWN_URL: ${DEFRA_ID_WELL_KNOWN_URL}
      DEFRA_ID_CLIENT_ID: ${DEFRA_ID_CLIENT_ID}
      DEFRA_ID_CLIENT_SECRET: ${DEFRA_ID_CLIENT_SECRET}
      DEFRA_ID_SERVICE_ID: ${DEFRA_ID_SERVICE_ID}
      DEFRA_ID_POLICY: ${DEFRA_ID_POLICY}
      DEFRA_ID_REDIRECT_URL: ${DEFRA_ID_REDIRECT_URL:-http://localhost:3010/sign-in-oidc}
      MESSAGE_HOST: ${MESSAGE_HOST}
      MESSAGE_USER: ${MESSAGE_USER}
      MESSAGE_PASSWORD: ${MESSAGE_PASSWORD}
      PROCESSOR_SUBSCRIPTION_ADDRESS: ${PROCESSOR_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}
      PROCESSOR_TOPIC_ADDRESS: ${PROCESSOR_TOPIC_ADDRESS}-${DEV_SUFFIX}
      MESSAGES_SUBSCRIPTION_ADDRESS: ${MESSAGES_SUBSCRIPTION_ADDRESS}-${DEV_SUFFIX}
      MESSAGES_TOPIC_ADDRESS: ${MESSAGES_TOPIC_ADDRESS}-${DEV_SUFFIX}
      SINGLE_FRONT_DOOR_URL: http://localhost:3000/landing-page/home
      DATA_HOST: ${DATA_HOST:-http://ffc-sfd-data:3004/graphql}
      FILE_PROCESSOR_DELETE_URL: ${FILE_PROCESSOR_DELETE_URL:-http://ffc-sfd-file-processor:3019/delete/}
      FILE_PROCESSOR_UPLOAD_URL: ${FILE_PROCESSOR_UPLOAD_URL:-http://ffc-sfd-file-processor:3019/upload/}
      FILE_PROCESSOR_DOWNLOAD_URL: ${FILE_PROCESSOR_DOWNLOAD_URL:-http://ffc-sfd-file-processor:3019/download/}
