- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING"
  type: "keyvault"
- key: DEFRA_ID_ENABLED
  value: "true"
- key: DEFRA_ID_WELL_KNOWN_URL
  value: "https://your-account.cpdev.cui.defra.gov.uk/idphub/b2c/b2c_1a_cui_cpdev_signupsigninsfi/.well-known/openid-configuration"
- key: DEFRA_ID_CLIENT_ID
  value: "{{servicename}}-DEFRA-ID-CLIENT-ID"
- key: DEFRA_ID_CLIENT_SECRET
  value: "{{servicename}}-DEFRA-ID-CLIENT-SECRET"
  type: "keyvault"
- key: DEFRA_ID_SERVICE_ID
  value: "{{servicename}}-DEFRA-ID-SERVICE-ID"
- key: DEFRA_ID_POLICY
  value: "b2c_1a_cui_cpdev_signupsigninsfi"
- key: DEFRA_ID_REDIRECT_URL
  value: "https://ffc-sfd-ahwp-stub.snd3.adp.defra.gov.uk/sign-in-oidc"
- key: DEFRA_ID_POST_LOGOUT_REDIRECT_URL
  value: "https://ffc-sfd-ahwp-stub.snd3.adp.defra.gov.uk/sign-out-oidc"
- key: COOKIE_PASSWORD
  value: "{{servicename}}-COOKIE-PASSWORD"
  type: "keyvault"
- key: MESSAGE_HOST
  value: "{{servicename}}-MESSAGE-HOST"
  type: "keyvault"
- key: PROCESSOR_TOPIC_ADDRESS
  value: "ffc-sfd-messages"
- key: SINGLE_FRONT_DOOR_URL
  value: "https://ffc-sfd-landing-page.snd3.adp.defra.gov.uk/landing-page"
